home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('halaman2/', views.halaman2, name='halaman2'),
]

story1applied/urls.py
from django.urls import path

from . import views

app_name = 'story1applied'

urlpatterns = [
    path('', views.index, name='index'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story5.urls')),
    path('story1applied/', include('story1applied.urls')),
    path('home/', include('home.urls'))
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.index, name='index'),
    path('addmatkul/', views.addmatkul, name='addmatkul'),
    path('deletematkul/<int:id>', views.deletematkul, name='deletematkul'),
    path('seematkul/<int:id>', views.seematkul, name='seematkul'),
]

home/models.py
from django.db import models

# Create your models here.

story1applied/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone

semesteran = [
    ("2019/2020 Gasal","2019/2020 Gasal"),
    ("2019/2020 Genap","2019/2020 Genap"),
    ("2020/2021 Gasal","2020/2021 Gasal"),
    ("2020/2021 Genap","2020/2021 Genap"),
    ("2021/2022 Gasal","2021/2022 Gasal"),
    ("2021/2022 Genap","2021/2022 Genap"),
    ("2022/2023 Gasal","2022/2023 Gasal"),
    ("2022/2023 Genap","2022/2023 Genap")
]

class matkuliah(models.Model):
    nama = models.TextField(max_length = 60)
    dosen = models.TextField(max_length = 60)
    sks = models.IntegerField()
    desc = models.TextField(max_length = 800)
    sems = models.TextField(choices = semesteran)
    ruangan = models.CharField(max_length = 60)

    def __str__(self):
        return "{} ({})".format(self.nama, self.dosen)

    def get_absolute_url(self):
        return reverse("story5:seematkul",args=[self.id])

story5/forms.py
from django.forms import ModelForm
from .models import matkuliah

class formatkul(ModelForm):
    class Meta:
        model = matkuliah
        fields = "__all__"

home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home/index.html')

def halaman2(request):
    return render(request, 'home/halaman2.html')

story1applied/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'story1applied/index.html')

story5/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import matkuliah
from .forms import formatkul

def index(request):
    diction = {
        'page' : 'index',
        'listmatkul' : matkuliah.objects.all().order_by("id")
    }
    return render(request, 'story5/index.html', diction)

def addmatkul(request):
    if request.method == 'POST':
        form_matkul = formatkul(request.POST)
        if form_matkul.is_valid():
            form_matkul.save()
            messages.add_message(request, messages.SUCCESS, 'Mata Kuliah {} telah ditambahkan'.format(request.POST['nama']))
        return redirect('story5:index')
    diction = {
        'page' : 'addmatkul'
    }
    return render(request, 'story5/addmatkul.html', diction)

def deletematkul(request, id):
    if request.method == 'POST':
        matakuliah = matkuliah.objects.get(id=id)
        matakuliah.delete()
        messages.add_message(request, messages.SUCCESS, 'Menghapus mata kuliah {} dari daftar'.format(matakuliah.nama))
    return redirect('story5:index')


def seematkul(request, id):
    diction = {
        'matakuliah' : matkuliah.objects.get(id=id)
    }

    return render(request, 'story5/seematkul.html', diction)

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'home/styles.css' %}">
        <script src="https://kit.fontawesome.com/yourcode.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>NomadLyfe</title>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-main sticky-top">
            <div class="container">
                <div class="row">
                    <img class="image-circle pfp" src="{% static 'images/profile.jpg' %}" alt="profile pic" style="padding-top: 2%; object-fit:cover; object-position: 0 0px;">
                    <a class="navbar-brand" href="#">   
                        <h2 class="tulisan">Nomad Jeff</h2>
                        <p class="tulisan">Steam ID: nomadWarrior13</p>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse" id="navbarNavAltMarkup">
                            <div class="navbar-nav mr-auto">
                                <a class="nav-item active" href="{% url 'home:index' %}">Home <span class="sr-only">(current)</span></a>
                                <a class="nav-item " href="{% url 'home:index' %}#about">About</a>
                                <a class="nav-item " href="{% url 'home:index' %}#container3">Experiences</a>
                                <a class="nav-item " href="{% url 'home:index' %}#contacter">Contact</a>
                                <a class="nav-item " href="{% url 'home:halaman2' %}">Favorite Movie</a>
                                <a class="nav-item " href="{% url 'story1applied:index' %}">Story 1</a>
                                <a class="nav-item " href="{% url 'story5:index' %}">Mata Kuliah</a>
                            </div>
                        </div>
                    </a>
                </div>
            
            </div>
        </nav>

        {% block content %}
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

home/templates/home/halaman2.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid bg-main2 h-with-nav">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-sm-12 p-2 d-flex align-items-center justify-content-center">
                <div class="about-box bg-main3 border-main4 p-2 text-center d-flex justify-content-center align-items-center flex-column" >
                    <a class="center" href="https://gogoanime.so/tenki-no-ko-episode-1">
                        <img src="{% static 'images/tenkinoko.jpg' %}" alt="tenki no ko" style="height: 360px; width: 260px;" style="margin: ;">
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-sm-12 p-2 d-flex align-items-center justify-content-center">
                <div class="about-box bg-main3 border-main4 p-2 text-center d-flex justify-content-center align-items-center flex-column" >
                    <a class="center" href="https://gogoanime.so/kimi-no-na-wa-episode-1">
                        <img src="{% static 'images/kiminonawa.jpg' %}" alt="kimi no nawa" style="height: 360px; width: 260px;" style="margin: ;">
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-sm-12 p-2 d-flex align-items-center justify-content-center">
                <div class="about-box bg-main3 border-main4 p-2 text-center d-flex justify-content-center align-items-center flex-column" >
                    <a class="center" href="https://gogoanime.so/koe-no-katachi-movie-episode-1">
                        <img src="{% static 'images/koenokatachi.jpeg' %}" alt="koe no katachi" style="height: 360px; width: 260px;" style="margin: ;">
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<div id="container2">
    <div class="col-lg-13" style="padding: 7%;" style="background-color: white;">
        <table class="table table-striped">
            <tr>
                <th>Interests</th>
                <th>Details</th>
                <th>Goals</th>
            </tr>
            <tr>
                <td>Linguistic</td>
                <td>I like learning new languages</td>
                <td>To learn 10 languages</td>
            </tr>
            <tr>
                <td>History</td>
                <td>I love mesopotamian history</td>
                <td>Finding out </td>
            </tr>
            <tr>
                <td>Politics</td>
                <td>I like hammurabbi's tactics and policies</td>
                <td>Able to read hammurabbi's codex</td>
            </tr>
            <tr>
                <td>Geography</td>
                <td>Learning about middle eastern terrain</td>
                <td>Learn more about iraqi climate</td>
            </tr>
            <tr>
                <td>Data Science</td>
                <td>I'm currently planning on learning data science</td>
                <td>Able to create my first AI</td>
            </tr>
            <tr>
                <td>WebDev</td>
                <td>Currently studying bootstrap</td>
                <td>Able to make my own website</td>
            </tr>
        </table>
    </div>
</div>


<div id="about">
    <div class="col" style="padding-left: 10%; padding-top: 2%; padding-bottom: 8%; background-color:rgb(59, 58, 58)">
        <div id="headinge">
            <h3 style="color: aliceblue;">About Me</h3>
        </div>
        <div class="container-fluid bg-main2 h-with-nav">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-sm-12 p-2 d-flex align-items-center justify-content-center">
                        <div class="about-box bg-main3 border-main4 p-2 text-center d-flex justify-content-center align-items-center flex-column" style="background-color: aliceblue;">
                            <img class="img-thumbnail" src="{% static 'images/bahasa.jpg' %}">
                            <h3 class="text-dark">Language Nerd</h3>
                            <h4 class="text-dark">
                                I like to learn new<br>languages.<br>I currently speak 5<br>fluently and planning to <br> learn more in the future
                            </h4>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-12 p-2 d-flex align-items-center justify-content-center">
                        <div class="about-box bg-main3 border-main4 p-2 text-center d-flex justify-content-center align-items-center flex-column" style="background-color: aliceblue;">
                            <img class="img-thumbnail" src="{% static 'images/francome.jpg' %}" style="height: -110%;">
                            <h3 class="text-dark">Biography</h3>
                            <h4 class="text-dark">
                                I am a student at <br>the University of Indonesia <br>Name : Nomad Jeff <br>Faculty : Computer Science <br>ID : 1906652000
                            </h4>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-12 p-2 d-flex align-items-center justify-content-center">
                        <div class="about-box bg-main3 border-main4 p-2 text-center d-flex justify-content-center align-items-center flex-column" style="background-color: aliceblue;">
                            <img class="img-thumbnail" src="{% static 'images/french.png' %}">
                            <h3 class="text-dark">Je Parle Français</h3>
                            <h4 class="text-dark">
                                Je suis Francophone mais <br>pas de la terre <br>francophone.<br> J'ai appris la langue<br>pour 5 mois seulement
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>


<div id="container3">
    <div class="col-lg-13" style="padding: 7%;" style="background-color: white;">
        <div id="headinge">
            <h3 style="color: aliceblue;">Experiences</h3>
        </div>
        
        <table class="table table-striped" style="background-color: aliceblue;">
            <tr>
                <th><h3>Portofolio</h3></th>
            </tr>
            <tr>
                <td>* Gold Medal, Computer Science competition in Asgardia</td>
            </tr>
            <tr>
                <td>* Nobel Award, The discovery of Dormammu's black dimention</td>
            </tr>
            <tr>
                <td>* The President of Nengushite Republic for 2 periods</td>
            </tr>
            <tr>
                <td>* WWE Championship, heavy weight championship</td>
            </tr>
            <tr>
                <td>* Invention, The invention of the two-headed stalagmite dragon</td>
            </tr>
            <tr>
                <td>* World's first professor to create 10.000 useless inventions</td>
            </tr>
        </table>
    </div>
</div>

<div id="contacter">
    <div id="contact-message">
        <h1> Me Contacter s'il vous plait<br>--------<>--------</h1>
    </div>
    <div class="social">
        <a href="https://gitlab.com/matthewsolomon_"><i class="fa fa-gitlab"></i></a>
        <a href="https://www.linkedin.com/mwlite/in/matthew-tumbur-parluhutan-solomon-siregar-55477b1ab"><i class="fa fa-linkedin"></i></a>
        <a href="https://www.instagram.com/matthewsolomon_/?hl=en"><i class="fa fa-instagram"></i></a>
        <a href="https://steamcommunity.com/id/mattvdb3/"><i class="fa fa-steam"></i></a>
    </div>
</div>
{% endblock %}

story1applied/templates/story1applied/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

    <head>
        <link rel="shortcut icon" type="image/png" href="https://listimg.pinclipart.com/picdir/s/519-5198165_pepehands-png-clipart.png">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'story1applied/style.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Matthew T.P. Solomon</title>
        <style>
            
            .fa {
                padding: 20px;
                font-size: 30px;
                width: 50px;
                text-align: center;
                text-decoration: none;
              }
              
        </style>
    </head>
    <body>
        <div class="center">
            <nav class="navbar navbar-expand-lg navbar-dark bg-main sticky-top">
                <div class="container">
                    <div class="row">
                        <a class="navbar-brand" href="#">   
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                                <div class="navbar-nav mb-auto">
                                    <a class="nav-item active" href="{% url 'home:index' %}">Home <span class="sr-only">(current)</span></a>
                                    <a class="nav-item " href="{% url 'home:index' %}#about">About</a>
                                    <a class="nav-item " href="{% url 'home:index' %}#container3">Experiences</a>
                                    <a class="nav-item " href="{% url 'home:index' %}#contacter">Contact</a>
                                    <a class="nav-item " href="{% url 'home:halaman2' %}">Favorite Movie</a>
                                    <a class="nav-item " href="#">Story 1</a>
                                    <a class="nav-item " href="{% url 'story5:index' %}">Mata Kuliah</a>
                                </div>
                            </div>
                        </a>
                    </div>
                
                </div>
            </nav>
            {% block content %}
            {% endblock %}
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        </div>
    </body>
</html>

story5/templates/story5/addmatkul.html
{% extends 'story5/base.html' %}
{% load static %}

{% block meta %}
<title>Add Matkul</title>
{% endblock meta %}

{% block content %}
<div class="main pt-3">
    <h2 class="text-center" style="color: rgb(14, 131, 233);">Add Mata Kuliah</h2>
    <div class="container" style="background-color: rgba(213, 5, 5, 0.292);">
        <div class="rounded-lg mb-3 p-3 card-form">
            <form action="{% url 'story5:addmatkul' %}" method="POST" style="object-position: left;">
                {%csrf_token%}
                <div class="form-group row">
                    <label for="nama-matkul" class="col-sm-2 col-form-label">Matkul</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="nama-matkul" placeholder="Mata kuliah" name="nama" required>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col">
                        <p class="p-auto m-auto">Semester</p>
                        <select class="form-control mb-1" name="sems" required>
                            <option value="2019/2020 Gasal">Gasal 2019/2020</option>
                            <option value="2019/2020 Genap">Genap 2019/2020</option>
                            <option value="2020/2021 Gasal">Gasal 2020/2021</option>
                            <option value="2020/2021 Genap">Genap 2020/2021</option>
                            <option value="2021/2022 Gasal">Gasal 2021/2022</option>
                            <option value="2021/2022 Genap">Genap 2021/2022</option>
                            <option value="2022/2023 Gasal">Gasal 2022/2023</option>
                            <option value="2022/2023 Genap">Genap 2022/2023</option>
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="ruangan-matkul" class="col-sm-2 col-form-label">Ruang Kelas</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="ruangan-matkul" placeholder="Nama/kode ruangan" name="ruangan" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="dosen-matkul" class="col-sm-2 col-form-label">Dosen</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="dosen-matkul" placeholder="Dosen pengajar" name="dosen" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="sks-matkul" class="col-sm-2 col-form-label">SKS</label>
                    <div class="col-sm-10">
                        <input type="number" min="1" max="10" placeholder="Masukkan angka 1-10" class="form-control" id="sks-matkul" name="sks" required>
                    </div>
                </div>
                <div class="form-group row">
                    <textarea placeholder="Deskripsi singkat mata kuliah (max 400 karakter)" class="form-control input-description p-2 m-4" name="desc" required></textarea>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10">
                      <button type="submit" class="btn btn-primary">Tambahkan Matkul Ini</button>
                    </div>
                </div>     
            </form>
        </div>
    </div>
</div>
{% endblock %}

story5/templates/story5/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'story5/styles.css' %}">
        <script src="https://kit.fontawesome.com/yourcode.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        {% block meta %}
        {% endblock meta %}
    </head>
    <body>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'story5:index' %}">Main Menu</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav ml-auto">

                    {% if page == "index" %}
                        <li class="nav-item active">
                            <a class="nav-link " href="{% url 'home:index' %}">Past Stories</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link " href="{% url 'story5:index' %}">Perkuliahan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'story5:addmatkul' %}">Tambah Matkul</a>
                        </li>
                    {% elif page == "add_page" %}
                        <li class="nav-item active">
                            <a class="nav-link " href="{% url 'home:index' %}">Past Stories</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link " href="{% url 'story5:index' %}">Perkuliahan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'story5:addmatkul' %}">Tambah Matkul</a>
                        </li>
                    {% else %}
                        <li class="nav-item active">
                            <a class="nav-link " href="{% url 'home:index' %}">Past Stories</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link " href="{% url 'story5:index' %}">Perkuliahan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'story5:addmatkul' %}">Tambah Matkul</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

story5/templates/story5/index.html
{% extends 'story5/base.html' %}
{% load static %}

{% block meta %}
<title>Front Page</title>
{% endblock meta %}


{% block content %}

<div class="container-fluid bg-main2 h-with-nav">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-sm-12 p-2 d-flex align-items-center justify-content-center">
                <div class="about-box bg-main3 border-main4 p-2 text-center d-flex justify-content-center align-items-center flex-column" style="background-color: aliceblue;">
                    <img class="img-thumbnail" src="{% static 'images/img2.jpg' %}" alt="foto" style="height: 360px; width: 260px;">
                    <h3 class="text-dark"><a class="nav-item " href="{% url 'story5:addmatkul' %}">Tambahkan Matkul</a></h3>
                </div>
            </div>
            <div class="col-lg-4 col-sm-12 p-2 d-flex align-items-center justify-content-center">
                <div class="about-box bg-main3 border-main4 p-2 text-center d-flex justify-content-center align-items-center flex-column" style="background-color: aliceblue;">
                    <img class="img-thumbnail" src="{% static 'images/img1.jpg' %}" alt="foto" style="height: 360px; width: 260px;">
                    <h3 class="text-dark"><a class="nav-item " href="{% url 'home:index' %}">Previous Stories</a></h3>
                </div>
            </div>
            <div class="col-lg-4 col-sm-12 p-2 d-flex align-items-center justify-content-center">
                <div class="about-box bg-main3 border-main4 p-2 text-center d-flex justify-content-center align-items-center flex-column" style="background-color: aliceblue;">
                    <img class="img-thumbnail" src="{% static 'images/img3.jpg' %}" alt="foto" style="height: 360px; width: 260px;">
                    <h3 class="text-dark"><a class="nav-item " href="{% url 'home:halaman2' %}">Hobby</a></h3>
                </div>
            </div>
        </div>

        <div style="text-align: center; font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; font-size: 50px;">
            <h1>Jadwal Kelas<br>--------<>--------</h1>
        </div>

        <div class="main pt-3">
            <div class="container">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{message.tags}} alert-dismissible show fade" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
                {% for matakuliah in listmatkul %}

                <div class="card-form p-3 row mb-3 rounded-lg" style="background-color: rgba(24, 56, 84, 0.163); margin: 2%; padding: 2%;">
                    <div class="col-9">
                        <h2 class="p-auto m-auto">
                        {{matakuliah.nama}}
                        </h2>
                        <p class="p-auto m-auto"> Ruangan : {{matakuliah.ruangan}}</p>
                        <a class="link-matkul" href="{{matakuliah.get_absolute_url}}">
                            <p class="p-auto m-auto">Informasi lebih lanjut</p>
                        </a>
                    </div>
                    <div class="col-3 d-flex justify-content-center align-items-center">
                        <form action="{% url 'story5:deletematkul' matakuliah.id %}" method="POST" class="mr-auto">
                            {% csrf_token %}
                            <button class="btn btn-danger mr-auto" type="input>">
                                Hapus
                            </button>
                        </form>
                    </div>
                </div>
                {% empty %}
                    <h2 class="text-center">Masukan data mata kuliah di kartu "Tambahkan Matkul"</a></h2>
                {% endfor %}
            </div>
        </div>
    </div>

</div>

{% endblock %}

story5/templates/story5/seematkul.html
{% extends 'story5/base.html' %}
{% load static %}

{% block meta %}
<title>See Matkul</title>
{% endblock meta %}
{% block content %}

<div class="main pt-3 mr-auto">
    <div class="container">
        <div class="back">
            <a href="{% url 'story5:index' %}"><-- Go Back</a>
        </div>
        <div class="rounded-lg mb-3 p-4 card-form" style="background-color: rgba(0, 46, 86, 0.224);">
            <h3>Mata Kuliah : {{ matakuliah.nama }}</h3>
            <div class="col p-auto m-auto">
                <p>Semester : {{ matakuliah.sems }}</p>
            </div>
            <div class="col p-auto m-auto">
                <p>Ruang : {{ matakuliah.ruangan }}</p>
            </div>
            <div class="col p-auto m-auto">
                <p>Dosen : {{ matakuliah.dosen }}</p>
            </div>
            <div class="col p-auto m-auto">
                <p>SKS : {{ matakuliah.sks }} SKS</p>
            </div>
            <div class="detail-description rounded-lg p-2">
                {{ matakuliah.desc }}
            </div>
        </div>
    </div>
</div>
{% endblock %}